version: '3.8'
services:
  backend:
    build: ./backend
    ports: ["8000:8000"]
    volumes:
      - ./backend:/app
    env_file: .env
  frontend:
    build: ./frontend
    ports: ["3000:3000"]
    volumes:
      - ./frontend:/app
      - /app/node_modules

# Removed invalid 'repos' section. Ensure pre-commit configuration is in a separate '.pre-commit-config.yaml' file.